### ISSUE TITLE
.env file

### ISSUE THREAD

**Issue by suhanmhd** [JatinAgrawal94/CareConnect#1]
.env file not found in assets folder 
pubspec issue

**Comment by Abdallah3030** [comment]
No file or variants found for asset: .env.


[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Instance of 'FileNotFoundError'
E/flutter (28863): #0      _getEntriesFromFile (package:flutter_dotenv/src/dotenv.dart:76:5)
E/flutter (28863): <asynchronous suspension>
E/flutter (28863): #1      load (package:flutter_dotenv/src/dotenv.dart:52:25)
E/flutter (28863): <asynchronous suspension>
E/flutter (28863): #2      main (package:careconnect/main.dart:41:3)

**Comment by Abdallah3030** [comment]
> .env file not found in assets folder pubspec issue

Did you solve it?

**Comment by JatinAgrawal94** [comment]
This issue is resolved now. Although you need to create your own firebase project and add your own credentials.
